[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Nightmare Foxy as a new Enemy ( V50 Compatible )"
websiteUrl = "https://github.com/FelixAllard/NightmareFoxy"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
TheWeavers-LethalBestiary = "1.2.1"
[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/NightmareFoxy.dll"
target = "plugins/FoxyNightmare/"

[[build.copy]]
source = "../../FoxyFnafUnity/AssetBundles/StandaloneWindows/foxymodasset"
target = "plugins/FoxyNightmare/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]